# image: python:2.7-alpine3.10
cache:
  paths:
    - src/data/apks
    - .pip
download_data:
  script:
    - cd ./src/data/ && ./download_pairs.py

build_report:
  artifacts:
    paths:
      - report/runs
    expire_in: 1000 years
  script:
    - pip --cache-dir=.pip install -r requirements.txt
    - cd ./src && ./main.py
