# image: python:2.7-alpine3.10
cache:
  paths:
    - src/data/apks
    - .pip
download_data:
  script:
    - cd ./src/data/ && ./download_pairs.py

build_report:
  script:
    - pip install -U pip
    - pip --cache-dir=.pip install requirements.txt
    - cd ./src && ./main.py
