# image: python:2.7-alpine3.10
cache:
  paths:
    - src/data/apks
download_data:
  script:
    - cd ./src/data/ && ./download_pairs.py

build_report:
  script:
    - python -V
    - pip -V
    - pip freeze
    - cd ./src && ./main.py
